import os
import tempfile


LEGACY_HELPER = (
    'import sys\n'
    'from importlib.machinery import PathFinder\n'
    '\n'
    '\n'
    'loader = PathFinder.find_module("AutomaticPackageReloader")\n'
    'mod = loader.load_module("AutomaticPackageReloader")\n'
    'sys.modules["AutomaticPackageReloader"] = mod\n'
    '\n'
    'from AutomaticPackageReloader import package_reloader as package_reloader38  # noqa\n'
    '\n'
    '\n'
    'class PackageReloader33ReloadCommand(package_reloader38.PackageReloaderReloadCommand):\n'
    '    pass\n'
).encode('utf-8')

HELPER = (
    'from AutomaticPackageReloader import package_reloader as package_reloader38  # noqa\n'
    '\n'
    '\n'
    'class PackageReloader33ReloadCommand(package_reloader38.PackageReloaderReloadCommand):\n'
    '    pass\n'
).encode('utf-8')

CONFIG = b'{"dependencies" : ["AutomaticPackageReloader"]}'
HELPER_NAME = 'package_reloader.py'
CONFIG_NAME = '.package_reloader.json'
HIDDEN_NAME = '.hidden-sublime-package'


def _generated_helper(data):
    return data.replace(b'\r\n', b'\n') in (LEGACY_HELPER, HELPER)


def ensure_helper(directory):
    """Create or update only the helper generated by AutomaticPackageReloader."""
    if os.path.islink(directory):
        return False
    os.makedirs(directory, exist_ok=True)
    helper_path = os.path.join(directory, HELPER_NAME)
    if os.path.islink(helper_path):
        return False

    try:
        with open(helper_path, 'rb') as stream:
            current = stream.read()
    except FileNotFoundError:
        try:
            with open(helper_path, 'xb') as stream:
                stream.write(HELPER)
        except FileExistsError:
            return False
    else:
        normalized = current.replace(b'\r\n', b'\n')
        if normalized == LEGACY_HELPER:
            descriptor, temp_path = tempfile.mkstemp(
                prefix='.package_reloader-', suffix='.tmp', dir=directory)
            try:
                with os.fdopen(descriptor, 'wb') as stream:
                    stream.write(HELPER)
                os.replace(temp_path, helper_path)
            finally:
                if os.path.exists(temp_path):
                    os.unlink(temp_path)
        elif normalized != HELPER:
            return False

    try:
        with open(os.path.join(directory, CONFIG_NAME), 'xb') as stream:
            stream.write(CONFIG)
    except FileExistsError:
        pass
    try:
        with open(os.path.join(directory, HIDDEN_NAME), 'xb'):
            pass
    except FileExistsError:
        pass
    return True


def cleanup_helper(directory):
    """Remove the generated helper only when its whole directory is owned."""
    if os.path.islink(directory):
        return False
    try:
        names = set(os.listdir(directory))
    except FileNotFoundError:
        return False

    owned_names = {HELPER_NAME, CONFIG_NAME, HIDDEN_NAME}
    if HELPER_NAME not in names or not names.issubset(owned_names):
        return False

    helper_path = os.path.join(directory, HELPER_NAME)
    if any(os.path.islink(os.path.join(directory, name)) for name in names):
        return False
    with open(helper_path, 'rb') as stream:
        if not _generated_helper(stream.read()):
            return False

    if CONFIG_NAME in names:
        with open(os.path.join(directory, CONFIG_NAME), 'rb') as stream:
            if stream.read() != CONFIG:
                return False
    if HIDDEN_NAME in names and os.path.getsize(os.path.join(directory, HIDDEN_NAME)):
        return False

    for name in names:
        os.unlink(os.path.join(directory, name))
    os.rmdir(directory)
    return True
